force-app/main/default/objects/DomainConfiguration__mdt/DomainConfiguration__mdt.object-meta.xml
<CustomObject>
    <label>DomainConfiguration</label>
    <pluralLabel>DomainConfigurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/DomainConfiguration__mdt/fields/DomainClassName__c.field-meta.xml
<CustomField>
    <fullName>DomainClassName__c</fullName>
    <label>DomainClassName</label>
    <length>35</length>
    <type>Text</type>
</CustomField>

force-app/main/framework/class/DomainService.cls
public class DomainService {

    public static ITriggerHandler getDomainImplementation(List<sObject> records){
        String objectType = String.valueOf(getSobjectType(records));
        return DomainService.getDomainClassHandler(objectType);
    }

    private static ITriggerHandler getDomainClassHandler(String objectName){
        
        DomainConfiguration__mdt domainConfig = DomainConfiguration__mdt.getInstance(objectName);
        if(domainConfig.isActive__c){
            return (ITriggerHandler) Type.forName(domainConfig.DomainClassName__c).newInstance();
        }
        
        return null;
    }

    private static Schema.SObjectType getSobjectType(List<sObject> records){
        return records.getSobjectType();
    }

}